---
jobs:
  build:
    if: "!contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # https://github.com/actions/checkout
      - uses: actions/setup-java@v3 # https://github.com/actions/setup-java
        with:
          cache: maven
          distribution: temurin
          java-version: "8"
      - run: ./mvnw --batch-mode --no-transfer-progress verify
name: Build and test
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
