---
jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # https://github.com/actions/checkout
      - uses: actions/setup-java@v4 # https://github.com/actions/setup-java
        with:
          cache: maven
          distribution: temurin
          java-version: "8"
      - run: ./mvnw --batch-mode --no-transfer-progress verify
name: Build and test
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
